name: Generate wiki [wiki update]
on:
  push:
    branches:
    - 'wiki_gen'

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: generate-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Setup venv
      run: python -m venv venv; ./venv/bin/pip install -r requirements.txt

    - name: Install wine (MDL decompiling) # it is still possible to use windows if phrase parsing is avoided but this might just be faster
      run: |
        sudo apt install wine64 xvfb

    - name: Download mrglaster/Source-models-decompiler-cmd (MDL decompiling)
      run: | 
        wget https://github.com/mrglaster/Source-models-decompiler-cmd/releases/download/Update/CrowbarDecompiler.1.1.zip
        unzip ./CrowbarDecompiler.1.1.zip
        chmod +x "./CrowbarDecompiler(1.1).exe"
        ls

    - name: Install assimp (SMD importing)
      run: sudo apt install libassimp-dev
    
    - name: Clone ZR repo
      run: git clone https://github.com/artvin01/TF2-Zombie-Riot

    - name: Parse ZR repo code
      env:
        DISPLAY: ":0.0"
      run: |
        Xvfb :0 -screen 0 1024x768x16 &
        ./venv/bin/python main.py
    
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: gh-pages/

  deploy:
    name: deploy-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5