name: Generate wiki [wiki update]
on:
  push:
    branches:
    - 'wiki_gen'

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    needs: decompile
    name: generate-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Setup venv
      run: python -m venv venv; ./venv/bin/pip install -r requirements.txt

    - name: Install wine # it is still possible to use windows if phrase parsing is avoided but this might just be faster
      run: |
        sudo dpkg --add-architecture i386
        wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        sudo apt install --install-recommends winehq-stable

    - name: Download CLI mdl decompiler
      run: | 
        wget https://github.com/mrglaster/Source-models-decompiler-cmd/releases/download/Update/CrowbarDecompiler.1.1.zip
        unzip ./CrowbarDecompiler.1.1.zip

    - name: Install assimp (SMD importing)
      run: sudo apt install assimp
    
    - name: Clone ZR repo
      run: git clone https://github.com/artvin01/TF2-Zombie-Riot

    - name: Parse ZR repo code
      run: ./venv/bin/python main.py
    
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v4
      with:
        path: gh-pages/

  deploy:
    name: deploy-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5